name: "Sync to forks (SSH)"

on:
  push:
    branches:
      - main
    tags:
      - "*"
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  sync:
    # only run from the source repo, so forks don't need secrets
    if: github.repository == 'yqkiuo/BreastSubtypeR'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "Start ssh-agent and add deploy keys"
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.MIRROR_DEPLOY_KEY }}       # org fork key
            ${{ secrets.MIRROR_DEPLOY_KEY_2 }}     # second account fork key

      - name: "Add GitHub to known_hosts"
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa,ecdsa,ed25519 github.com >> ~/.ssh/known_hosts

      - name: "Configure git"
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: "Add remotes"
        run: |
          git remote add mirror_org   git@github.com:JohanHartmanGroupBioteam/BreastSubtypeR.git
          git remote add mirror_user  git@github.com:<SecondAccount>/BreastSubtypeR.git
          git remote -v

      - name: "Push main and tags to both forks (no force)"
        run: |
          set -e
          git push mirror_org  HEAD:refs/heads/main
          git push mirror_org  --tags
          git push mirror_user HEAD:refs/heads/main
          git push mirror_user --tags
