name: "Sync to two forks (SSH)"

on:
  push:
    branches: [ main ]
    tags: [ "*" ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  sync:
    if: github.repository == 'yqkiuo/BreastSubtypeR'   # run only in the source repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      # Start ssh-agent and PERSIST its env to later steps
      - name: Start ssh-agent
        run: |
          eval "$(ssh-agent -s)"
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
          echo "SSH_AGENT_PID=$SSH_AGENT_PID" >> $GITHUB_ENV

      - name: Assert secrets exist
        run: |
          [ -n "${{ secrets.MIRROR_DEPLOY_KEY }}" ] || { echo "::error:: Secret MIRROR_DEPLOY_KEY is missing"; exit 1; }
          [ -n "${{ secrets.MIRROR_DEPLOY_KEY_2_SIFAKISE }}" ] || { echo "::error:: Secret MIRROR_DEPLOY_KEY_2_SIFAKISE is missing"; exit 1; }

      # Add OpenSSH private keys, stripping CRLF if present
      - name: Add deploy key for org fork
        run: |
          printf '%s' "${{ secrets.MIRROR_DEPLOY_KEY }}" | tr -d '\r' > /tmp/key_org
          chmod 600 /tmp/key_org
          ssh-add /tmp/key_org

      - name: Add deploy key for user fork (sifakise)
        run: |
          printf '%s' "${{ secrets.MIRROR_DEPLOY_KEY_2_SIFAKISE }}" | tr -d '\r' > /tmp/key_user
          chmod 600 /tmp/key_user
          ssh-add /tmp/key_user

      - name: Add GitHub to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keysca
