name: "Sync to org fork"

on:
  push:
    branches:
      - main
    tags:
      - "*"
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: "Preflight - verify token can reach target repo (expect 200)"
        env:
          TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          set -euo pipefail
          HTTP=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer $TOKEN" \
            https://api.github.com/repos/JohanHartmanGroupBioteam/BreastSubtypeR)
          echo "GitHub API returned: $HTTP"
          if [ "$HTTP" != "200" ]; then
            echo "::error:: Token cannot access repo. Expected HTTP 200 but got $HTTP."
            echo "::error:: Check: token type=fine-grained; resource owner=JohanHartmanGroupBioteam; repo selected=BreastSubtypeR; permission=Contents: Read & Write; token not expired."
            exit 1
          fi

      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "Configure git"
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: "Add mirror remote"
        env:
          TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          git remote add mirror https://x-access-token:${TOKEN}@github.com/JohanHartmanGroupBioteam/BreastSubtypeR.git
          git remote -v

      - name: "Push main and tags (no force)"
        run: |
          set -e
          git push mirror HEAD:refs/heads/main
          git push --tags mirror
