name: "Sync to org fork (SSH)"

on:
  push:
    branches:
      - main
    tags:
      - "*"
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "Start ssh-agent and add deploy key"
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MIRROR_DEPLOY_KEY }}

      - name: "Add GitHub to known_hosts"
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa,ecdsa,ed25519 github.com >> ~/.ssh/known_hosts

      - name: "Configure git"
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: "Add mirror remote (SSH)"
        run: |
          git remote add mirror git@github.com:JohanHartmanGroupBioteam/BreastSubtypeR.git
          git remote -v

      - name: "Push main and tags (no force)"
        run: |
          set -e
          git push mirror HEAD:refs/heads/main
          git push --tags mirror
